---
- hosts: all
  become: true

  tasks:
    - name: Make sure openssl and openssh are updted
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - openssl
        - openssh
      ignore_errors: yes
    - name: Check if docker is installed
      ansible.builtin.command: docker --version
      register: output
      ignore_errors: yes
    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: present
      when:
        output.failed
